### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2855: ordinal not in range(128)

### ISSUE THREAD

**Issue by xiucz** [everestial/VCF-Simplify#4]
Hi, 

Thank you for your vcf pharsing tool, when I use this script to simplify vep or annovar annotated vcf, it reports bug
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2855: ordinal not in range(128)
```

**Comment by everestial** [comment]
That error must be related to cyvcf2 module. VCF-Simplify is updated and does not use `cyvcf2` module anymore. 
You may use the updated VCFsimplify and report if any error arises.
