### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by asteppke** [everestial/VCF-Simplify#6]
After cloning the repo and starting VCF-Simplify in Windows I receive the following message:

````
C:\Users\alexander\VCF-Simplify>python VcfSimplify.py -h
Traceback (most recent call last):
  File "VcfSimplify.py", line 12, in <module>
    from assign_task.perform_operation import vcf_solver
  File "C:\Users\alexander\VCF-Simplify\assign_task\perform_operation.py", line 6, in <module>
    from metadata_parser.utils import vcf_records_as_table
  File "C:\Users\alexander\VCF-Simplify\metadata_parser\utils.py", line 4, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
````

The `resource` module does not exist in CPython under Windows. As far as I know there is also no equivalent replacement so disabling this functionality lets the application run fine.

A small patch (https://github.com/everestial/VCF-Simplify/pull/7) can achieve that.

**Comment by everestial** [comment]
@asteppke 
Thanks for highlighting the issue. I was aware of this problem, but never got back to you again. I will review the code changes and merge it. 

May I know how are you using VCF-Simplify? I just want to get some feedback. 

Thanks ! :)

**Comment by asteppke** [comment]
I am helping to use VCF-Simplify to look at genetic data of plants, especially trees. 

The group was using an opaque Perl script before and VCF-Simplify looks like a much nicer replacement. As many people are using Windows as their desktop OS of course we would appreciate if compatibility on many platforms is included.

**Comment by everestial** [comment]
The issue is now resolved. 
Thanks you for bringing this up.
