### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by vappiah** [everestial/VCF-Simplify#9]
Hi

When I use python 3.5  and 3.6 to run  VcfSimplify.py on my sample I get this error

python 3.5 
Traceback (most recent call last):
File "VcfSimplify.py", line 12, in <module>
    from assign_task.perform_operation import vcf_solver
  File "/home/user/analysis/ariantcalling/pop_gene/VCF-Simplify/assign_task/perform_operation.py", line 76
    print(f"ViewVCF run time = {run_time : .4f} seconds.")

When I use python 3.6 I get this error
Using the following arguments: 
Namespace(GTbase=['GT:numeric'], PG='GT', PI='PI', formats=['all'], inVCF='final.vcf', includeUnphased='yes', infos=['all'], mode='0', outFile='final.hap.txt', outHeaderName='final.header.txt', preHeader=['all'], samples='all', toType=['haplotype'])

Using option "SimplifyVCF"
  Simplifying the VCF records ...
Creating Haplotype file from VCF file
0 samples found

Writing the header to a separate output file.

sample genotypes tag 'GT' are written as 'numeric' bases
parsing records ... 
elapsed time:  0.011363744735717773

fnc_vcf_to_haplotype: memory before: 7,996, after: 8,080, consumed: 84; exec time: 0.011483907699584961 seconds

Below are the respective commands I used.

python3.5 VCF-Simplify/VcfSimplify.py SimplifyVCF -toType haplotype -inVCF final.vcf -outFile final.hap.txt -outHeaderName final.header.txt -PI PI -PG GT -includeUnphased yes

python3.6 VCF-Simplify/VcfSimplify.py SimplifyVCF -toType haplotype -inVCF final.vcf -outFile final.hap.txt -outHeaderName final.header.txt -PI PI -PG GT -includeUnphased yes

**Comment by bhuwanaryal19** [comment]
Hi @jotes35 :
You need to use python3.6 + to use this program as it contains f-string which was introduced in python. Your output shows it is working in python 3.6. Try changing outputfile and see if output file is populated.

**Comment by everestial** [comment]
@jotes35 
The terminal output you are receiving when using 3.5 is an error. This is simply due to version issue and you should not be using python 3.5

**The terminal output you are receiving when using 3.6 is not an errror, infact it is a valid terminal message. You must have received a proper "final.hap.txt" file with  your second run.** 

Let me know if you have any questions. 

Thanks,
Bishwa K.
